### ISSUE TITLE
Add GitHub actions integration

### ISSUE THREAD

**Issue by ddiez** [alexisvdb/singleCellHaystack#12]
Add Travis integration to have automatic testing when we push changes to the repository.

**Comment by ddiez** [comment]
I changed this old issue's title to add github actions integration as that seems to be the recommended way now.

**Comment by alexisvdb** [comment]
#

**Comment by ddiez** [comment]
Added here: 1694353a0b6de6f3d3ffcb283d91a2e92a93f2c1
