### ISSUE TITLE
randomization non-linear runtime with >> numbers of input cells?

### ISSUE THREAD

**Issue by davemcg** [alexisvdb/singleCellHaystack#16]
I'm running `Haystack` with 985k cells. It took about 8 hours to do the ` Kullback-Leibler divergences...`. After another 4 hours the `randomizations` step was at around 30 percent. 12 more hours later we are at 48%. I think it took about 4 hours to  go from 46 -> 48%. 

It *seems* like the `randomization` step slows as it progresses. My understanding was that this step should proceed at a linear, consistent rate as essentially it is just picking (semi) random genes to compare the DKL results against?

Anyways, I'm going to have to restart the job as I am running it on a HPC node with a walltime limit of 36 hours. Just wanted to check whether my observation makes any sense.

**Comment by alexisvdb** [comment]
Hi David,

We think your understanding is correct: this step should be linear. We checked the progress of the randomization step on a dataset of 100k cells, tracking the progress every few minutes. We saw that the progress was almost perfectly linear in time. So, we think this step should not be slowing down.

I know it's time consuming but could you please check if you ca reproduce the problem?

**Comment by davemcg** [comment]
Is there a more rigorous way to log the randomization % done timing? 

Otherwise I'll run with a few hundred thousand cells and just log it periodically.

**Comment by davemcg** [comment]
![plot_zoom_png](https://user-images.githubusercontent.com/10225430/93519234-00f93300-f8fc-11ea-882f-f09653a9bd59.png)

Still awaiting the randomization to finish but clearing it is not linear in time run.

300,000 cells.

**Comment by ddiez** [comment]
Are you using advance sampling? Would help to see the code you used to run haystack here.

**Comment by ddiez** [comment]
We found the likely issue. Will keep you posted here!

**Comment by ddiez** [comment]
@davemcg we found that during advance sampling `sample` function becomes the bottleneck.

```
> system.time({sample(1:100, prob = 1:100)})
   user  system elapsed 
      0       0       0 
> system.time({sample(1:100000, prob = 1:100000)})
   user  system elapsed 
  2.673   0.004   2.678 
> system.time({sample(1:300000, prob = 1:300000)})
   user  system elapsed 
 24.151   0.030  24.211 
```

We are trying now an implementation in the `wrswoR` package. It is very fast and gives near identical results in the few tests we did:

```
> system.time({wrswoR::sample_int_expj(300000, 300000, prob = 1:300000)})
   user  system elapsed 
  0.050   0.000   0.051
```

If you want to test this you need to install the `wrswoR` branch and also the `wrswoR` package from CRAN.

**Comment by davemcg** [comment]
Damnit, many apologies for not mentioning I was using `advanced sampling`.

I'll install the branch and give it a go.

**Comment by davemcg** [comment]
I haven't evaluated whether the results are the same, but the runtime is DRAMATICALLY faster.

With 300k cells went from 16.5 hours to 3 hours.

Thanks for following up on this. I'll leave it to you to close the issue.
